In [1]:
import numpy as np
from autograd import Tensor
import torch

In [2]:
X = Tensor(np.arange(1, 17).reshape(4, 4), name="X")
W = Tensor(np.eye(X.shape[0]) * 2, name="W1", requires_grad=True)
b = Tensor(np.arange(X.shape[0]), name="b1", requires_grad=True)

out = ((W @ X + b)**2).sum()
out.backward()

out.draw_computation_graph()
W

tensor([[2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 2.]], dtype=float32, requires_grad=True)

In [3]:
X = torch.tensor(X.data)
W = torch.tensor(W.data, requires_grad=True)
b = torch.tensor(b.data, requires_grad=True)

out = torch.sum((W @ X + b)**2)
out.backward()
out, X.grad, W.grad, b.grad

(tensor(6936., grad_fn=<SumBackward0>),
 None,
 tensor([[ 160.,  368.,  576.,  784.],
         [ 320.,  784., 1248., 1712.],
         [ 480., 1200., 1920., 2640.],
         [ 640., 1616., 2592., 3568.]]),
 tensor([112., 136., 160., 184.]))

In [4]:
W

tensor([[2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 2.]], requires_grad=True)